version: "3.8"
services:

  rabbitmq:
    image: rabbitmq:3.10-management
    environment:
      RABBITMQ_DEFAULT_USER: "my_user"
      RABBITMQ_DEFAULT_PASS: "my_password"
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  summarizer:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      PROJECT_NAME: "zeroshot_summarizer"
      PYTHONPATH: /home/
    ports:
      - "8383:8000"
    command: bash /home/app/start.sh
    links:
      - rabbitmq
    volumes:
      - ./models:/home/models
      - ./huggingface_models:/root/.cache/huggingface/
    depends_on:
      - rabbitmq
    restart: on-failure

  consumer:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: consumer/Dockerfile
    environment:
      PYTHONPATH: /home/
    command: bash /home/consumer/start.sh
    links:
      - rabbitmq
    volumes:
      - ./models:/home/models
      - ./huggingface_models:/root/.cache/huggingface/
    depends_on:
      - summarizer
      - rabbitmq
    restart: on-failure
