version: "3.8"
services:
  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:3.10-management
    environment:
      RABBITMQ_DEFAULT_USER: "my_user"
      RABBITMQ_DEFAULT_PASS: "my_password"
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  summarizer:
    build: .
    environment:
      PROJECT_NAME: "zeroshot_summarizer"
      PYTHONPATH: .:app
    ports:
      - "8383:8000"
    command: bash start.sh
    links:
      - redis
      - rabbitmq
    volumes:
      - ./models:/home/models
    depends_on:
      - rabbitmq
      - redis
    restart: on-failure
