version: "3.11"
services:
  redis:
    image: redis:latest
    networks:
      - docker_net_1

  rabbitmq:
    image: rabbitmq:3.10-management
    environment:
      RABBITMQ_DEFAULT_USER: "my_user"
      RABBITMQ_DEFAULT_PASS: "my_password"
    ports:
      - "5672:5672"
    networks:
      - docker_net_1

  summarizer:
    build: .
    environment:
      PROJECT_NAME: "zeroshot_summarizer"
      PYTHONPATH: .:app
    ports:
      - "8383:8000"
    command: bash start.sh
    networks:
      - docker_net_1
    volumes:
      - ./models:/home/models
    depends_on:
      - rabbitmq
      - redis
    restart: on-failure

networks:
  docker_net_1:
    name: summarizer-network
