version: "3.8"
services:

  rabbitmq:
    image: rabbitmq:3.10-management
    environment:
      RABBITMQ_DEFAULT_USER: "my_user"
      RABBITMQ_DEFAULT_PASS: "my_password"
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  summarizer:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      PROJECT_NAME: "zeroshot_summarizer"
      PYTHONPATH: /home/
      WAIT_HOSTS: rabbitmq:5672
    ports:
      - "8383:8000"
    command: bash /home/app/start.sh
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    environment:
      PYTHONPATH: /home/
      WAIT_HOSTS: rabbitmq:5672, summarizer:8000
    command: bash /home/consumer/start.sh
    links:
      - rabbitmq
    volumes:
      - ./models:/home/models
      - ./huggingface_models:/root/.cache/huggingface/
    depends_on:
      - rabbitmq
      - summarizer
    restart: on-failure
